name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-clj:
    strategy:
      matrix:
        # Supported Java versions: LTS releases 8 and 11 and the latest release
        jdk: [ 8, 11, 15 ]

    name: Clojure (Java ${{ matrix.jdk }})

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.jdk }}
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.jdk }}
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
      - name: Run tests
        run: clojure -M:test -m kaocha.runner
